--Input for JBOOST generated by Excel
--    Definition Modelname
local	ModelName="Struct"
--    Definition der FE-Knoten
os_FeNode{model=ModelName	,node=501	,x=0	,y=0	,z=-80.43	,pMass=000000	,pInertia=0	,pOutOfVertically=00.000}
os_FeNode{model=ModelName	,node=502	,x=0	,y=0	,z=-77.43	,pMass=000000	,pInertia=0	,pOutOfVertically=00.039}
os_FeNode{model=ModelName	,node=503	,x=0	,y=0	,z=-74.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.080}
os_FeNode{model=ModelName	,node=504	,x=0	,y=0	,z=-71.00	,pMass=000000	,pInertia=0	,pOutOfVertically=00.123}
os_FeNode{model=ModelName	,node=505	,x=0	,y=0	,z=-67.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.172}
os_FeNode{model=ModelName	,node=506	,x=0	,y=0	,z=-63.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.224}
os_FeNode{model=ModelName	,node=507	,x=0	,y=0	,z=-59.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.277}
os_FeNode{model=ModelName	,node=508	,x=0	,y=0	,z=-55.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.329}
os_FeNode{model=ModelName	,node=509	,x=0	,y=0	,z=-51.70	,pMass=000000	,pInertia=0	,pOutOfVertically=00.376}
os_FeNode{model=ModelName	,node=510	,x=0	,y=0	,z=-48.50	,pMass=000000	,pInertia=0	,pOutOfVertically=00.418}
os_FeNode{model=ModelName	,node=511	,x=0	,y=0	,z=-45.20	,pMass=000001	,pInertia=0	,pOutOfVertically=00.461}
os_FeNode{model=ModelName	,node=512	,x=0	,y=0	,z=-41.90	,pMass=000000	,pInertia=0	,pOutOfVertically=00.504}
os_FeNode{model=ModelName	,node=513	,x=0	,y=0	,z=-38.60	,pMass=000000	,pInertia=0	,pOutOfVertically=00.548}
os_FeNode{model=ModelName	,node=514	,x=0	,y=0	,z=-35.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.591}
os_FeNode{model=ModelName	,node=515	,x=0	,y=0	,z=-31.80	,pMass=000000	,pInertia=0	,pOutOfVertically=00.637}
os_FeNode{model=ModelName	,node=516	,x=0	,y=0	,z=-28.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.682}
os_FeNode{model=ModelName	,node=517	,x=0	,y=0	,z=-24.80	,pMass=000000	,pInertia=0	,pOutOfVertically=00.728}
os_FeNode{model=ModelName	,node=518	,x=0	,y=0	,z=-21.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.774}
os_FeNode{model=ModelName	,node=519	,x=0	,y=0	,z=-17.80	,pMass=000000	,pInertia=0	,pOutOfVertically=00.820}
os_FeNode{model=ModelName	,node=520	,x=0	,y=0	,z=-14.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.866}
os_FeNode{model=ModelName	,node=521	,x=0	,y=0	,z=-10.80	,pMass=000000	,pInertia=0	,pOutOfVertically=00.911}
os_FeNode{model=ModelName	,node=522	,x=0	,y=0	,z=-7.30	,pMass=000001	,pInertia=0	,pOutOfVertically=00.957}
os_FeNode{model=ModelName	,node=523	,x=0	,y=0	,z=-3.80	,pMass=000000	,pInertia=0	,pOutOfVertically=01.003}
os_FeNode{model=ModelName	,node=524	,x=0	,y=0	,z=-0.60	,pMass=028169	,pInertia=0	,pOutOfVertically=01.045}
os_FeNode{model=ModelName	,node=525	,x=0	,y=0	,z=02.60	,pMass=142156	,pInertia=0	,pOutOfVertically=01.087}
os_FeNode{model=ModelName	,node=526	,x=0	,y=0	,z=05.80	,pMass=008875	,pInertia=0	,pOutOfVertically=01.129}
os_FeNode{model=ModelName	,node=527	,x=0	,y=0	,z=07.50	,pMass=000625	,pInertia=0	,pOutOfVertically=01.144}
os_FeNode{model=ModelName	,node=528	,x=0	,y=0	,z=11.50	,pMass=023770	,pInertia=0	,pOutOfVertically=01.178}
os_FeNode{model=ModelName	,node=529	,x=0	,y=0	,z=15.47	,pMass=005605	,pInertia=0	,pOutOfVertically=01.213}
os_FeNode{model=ModelName	,node=530	,x=0	,y=0	,z=15.62	,pMass=000000	,pInertia=0	,pOutOfVertically=01.214}
os_FeNode{model=ModelName	,node=531	,x=0	,y=0	,z=15.68	,pMass=009735	,pInertia=0	,pOutOfVertically=01.214}
os_FeNode{model=ModelName	,node=532	,x=0	,y=0	,z=17.07	,pMass=000765	,pInertia=0	,pOutOfVertically=01.221}
os_FeNode{model=ModelName	,node=533	,x=0	,y=0	,z=17.47	,pMass=000000	,pInertia=0	,pOutOfVertically=01.223}
os_FeNode{model=ModelName	,node=534	,x=0	,y=0	,z=19.99	,pMass=000000	,pInertia=0	,pOutOfVertically=01.236}
os_FeNode{model=ModelName	,node=535	,x=0	,y=0	,z=22.07	,pMass=000000	,pInertia=0	,pOutOfVertically=01.246}
os_FeNode{model=ModelName	,node=536	,x=0	,y=0	,z=24.99	,pMass=000000	,pInertia=0	,pOutOfVertically=01.261}
os_FeNode{model=ModelName	,node=537	,x=0	,y=0	,z=27.92	,pMass=000000	,pInertia=0	,pOutOfVertically=01.275}
os_FeNode{model=ModelName	,node=538	,x=0	,y=0	,z=30.84	,pMass=000000	,pInertia=0	,pOutOfVertically=01.290}
os_FeNode{model=ModelName	,node=539	,x=0	,y=0	,z=33.77	,pMass=000000	,pInertia=0	,pOutOfVertically=01.305}
os_FeNode{model=ModelName	,node=540	,x=0	,y=0	,z=36.69	,pMass=001083	,pInertia=0	,pOutOfVertically=01.319}
os_FeNode{model=ModelName	,node=541	,x=0	,y=0	,z=38.49	,pMass=011686	,pInertia=0	,pOutOfVertically=01.328}
os_FeNode{model=ModelName	,node=542	,x=0	,y=0	,z=39.60	,pMass=003197	,pInertia=0	,pOutOfVertically=01.334}
os_FeNode{model=ModelName	,node=543	,x=0	,y=0	,z=39.64	,pMass=000000	,pInertia=0	,pOutOfVertically=01.334}
os_FeNode{model=ModelName	,node=544	,x=0	,y=0	,z=39.78	,pMass=000000	,pInertia=0	,pOutOfVertically=01.335}
os_FeNode{model=ModelName	,node=545	,x=0	,y=0	,z=39.92	,pMass=000000	,pInertia=0	,pOutOfVertically=01.335}
os_FeNode{model=ModelName	,node=546	,x=0	,y=0	,z=39.97	,pMass=000000	,pInertia=0	,pOutOfVertically=01.336}
os_FeNode{model=ModelName	,node=547	,x=0	,y=0	,z=42.72	,pMass=000000	,pInertia=0	,pOutOfVertically=01.349}
os_FeNode{model=ModelName	,node=548	,x=0	,y=0	,z=45.46	,pMass=000000	,pInertia=0	,pOutOfVertically=01.363}
os_FeNode{model=ModelName	,node=549	,x=0	,y=0	,z=48.21	,pMass=000000	,pInertia=0	,pOutOfVertically=01.377}
os_FeNode{model=ModelName	,node=550	,x=0	,y=0	,z=50.97	,pMass=000000	,pInertia=0	,pOutOfVertically=01.391}
os_FeNode{model=ModelName	,node=551	,x=0	,y=0	,z=53.72	,pMass=000000	,pInertia=0	,pOutOfVertically=01.404}
os_FeNode{model=ModelName	,node=552	,x=0	,y=0	,z=56.47	,pMass=000000	,pInertia=0	,pOutOfVertically=01.418}
os_FeNode{model=ModelName	,node=553	,x=0	,y=0	,z=59.23	,pMass=000000	,pInertia=0	,pOutOfVertically=01.432}
os_FeNode{model=ModelName	,node=554	,x=0	,y=0	,z=61.99	,pMass=000000	,pInertia=0	,pOutOfVertically=01.446}
os_FeNode{model=ModelName	,node=555	,x=0	,y=0	,z=64.74	,pMass=000000	,pInertia=0	,pOutOfVertically=01.459}
os_FeNode{model=ModelName	,node=556	,x=0	,y=0	,z=67.50	,pMass=000000	,pInertia=0	,pOutOfVertically=01.473}
os_FeNode{model=ModelName	,node=557	,x=0	,y=0	,z=70.26	,pMass=000875	,pInertia=0	,pOutOfVertically=01.487}
os_FeNode{model=ModelName	,node=558	,x=0	,y=0	,z=71.46	,pMass=009506	,pInertia=0	,pOutOfVertically=01.493}
os_FeNode{model=ModelName	,node=559	,x=0	,y=0	,z=72.59	,pMass=002689	,pInertia=0	,pOutOfVertically=01.499}
os_FeNode{model=ModelName	,node=560	,x=0	,y=0	,z=72.63	,pMass=000000	,pInertia=0	,pOutOfVertically=01.499}
os_FeNode{model=ModelName	,node=561	,x=0	,y=0	,z=72.76	,pMass=000000	,pInertia=0	,pOutOfVertically=01.500}
os_FeNode{model=ModelName	,node=562	,x=0	,y=0	,z=72.89	,pMass=000000	,pInertia=0	,pOutOfVertically=01.500}
os_FeNode{model=ModelName	,node=563	,x=0	,y=0	,z=72.94	,pMass=000000	,pInertia=0	,pOutOfVertically=01.500}
os_FeNode{model=ModelName	,node=564	,x=0	,y=0	,z=75.70	,pMass=000000	,pInertia=0	,pOutOfVertically=01.514}
os_FeNode{model=ModelName	,node=565	,x=0	,y=0	,z=78.46	,pMass=000000	,pInertia=0	,pOutOfVertically=01.528}
os_FeNode{model=ModelName	,node=566	,x=0	,y=0	,z=81.22	,pMass=000000	,pInertia=0	,pOutOfVertically=01.542}
os_FeNode{model=ModelName	,node=567	,x=0	,y=0	,z=83.99	,pMass=000000	,pInertia=0	,pOutOfVertically=01.556}
os_FeNode{model=ModelName	,node=568	,x=0	,y=0	,z=86.76	,pMass=000000	,pInertia=0	,pOutOfVertically=01.570}
os_FeNode{model=ModelName	,node=569	,x=0	,y=0	,z=89.52	,pMass=000000	,pInertia=0	,pOutOfVertically=01.583}
os_FeNode{model=ModelName	,node=570	,x=0	,y=0	,z=92.29	,pMass=000000	,pInertia=0	,pOutOfVertically=01.597}
os_FeNode{model=ModelName	,node=571	,x=0	,y=0	,z=95.06	,pMass=000000	,pInertia=0	,pOutOfVertically=01.611}
os_FeNode{model=ModelName	,node=572	,x=0	,y=0	,z=97.84	,pMass=000000	,pInertia=0	,pOutOfVertically=01.625}
os_FeNode{model=ModelName	,node=573	,x=0	,y=0	,z=100.61	,pMass=000000	,pInertia=0	,pOutOfVertically=01.639}
os_FeNode{model=ModelName	,node=574	,x=0	,y=0	,z=103.39	,pMass=000000	,pInertia=0	,pOutOfVertically=01.653}
os_FeNode{model=ModelName	,node=575	,x=0	,y=0	,z=106.16	,pMass=001193	,pInertia=0	,pOutOfVertically=01.667}
os_FeNode{model=ModelName	,node=576	,x=0	,y=0	,z=107.58	,pMass=000307	,pInertia=0	,pOutOfVertically=01.674}
os_FeNode{model=ModelName	,node=577	,x=0	,y=0	,z=107.79	,pMass=006212	,pInertia=0	,pOutOfVertically=01.675}
os_FeNode{model=ModelName	,node=578	,x=0	,y=0	,z=108.94	,pMass=002100	,pInertia=0	,pOutOfVertically=01.680}
os_FeNode{model=ModelName	,node=579	,x=0	,y=0	,z=108.97	,pMass=000000	,pInertia=0	,pOutOfVertically=01.681}
os_FeNode{model=ModelName	,node=580	,x=0	,y=0	,z=109.09	,pMass=000000	,pInertia=0	,pOutOfVertically=01.681}
os_FeNode{model=ModelName	,node=581	,x=0	,y=0	,z=109.21	,pMass=000000	,pInertia=0	,pOutOfVertically=01.682}
os_FeNode{model=ModelName	,node=582	,x=0	,y=0	,z=109.24	,pMass=000000	,pInertia=0	,pOutOfVertically=01.682}
os_FeNode{model=ModelName	,node=583	,x=0	,y=0	,z=112.02	,pMass=030000	,pInertia=0	,pOutOfVertically=01.696}
os_FeNode{model=ModelName	,node=584	,x=0	,y=0	,z=114.80	,pMass=000000	,pInertia=0	,pOutOfVertically=01.710}
os_FeNode{model=ModelName	,node=585	,x=0	,y=0	,z=117.58	,pMass=000000	,pInertia=0	,pOutOfVertically=01.724}
os_FeNode{model=ModelName	,node=586	,x=0	,y=0	,z=120.36	,pMass=000000	,pInertia=0	,pOutOfVertically=01.738}
os_FeNode{model=ModelName	,node=587	,x=0	,y=0	,z=123.14	,pMass=000000	,pInertia=0	,pOutOfVertically=01.751}
os_FeNode{model=ModelName	,node=588	,x=0	,y=0	,z=125.92	,pMass=000819	,pInertia=0	,pOutOfVertically=01.765}
os_FeNode{model=ModelName	,node=589	,x=0	,y=0	,z=128.68	,pMass=000181	,pInertia=0	,pOutOfVertically=01.779}
os_FeNode{model=ModelName	,node=590	,x=0	,y=0	,z=128.71	,pMass=018658	,pInertia=0	,pOutOfVertically=01.779}
os_FeNode{model=ModelName	,node=591	,x=0	,y=0	,z=130.68	,pMass=006342	,pInertia=0	,pOutOfVertically=01.789}
os_FeNode{model=ModelName	,node=592	,x=0	,y=0	,z=131.49	,pMass=001139	,pInertia=0	,pOutOfVertically=01.793}
os_FeNode{model=ModelName	,node=593	,x=0	,y=0	,z=133.57	,pMass=000361	,pInertia=0	,pOutOfVertically=01.804}
os_FeNode{model=ModelName	,node=594	,x=0	,y=0	,z=133.69	,pMass=001436	,pInertia=0	,pOutOfVertically=01.804}
os_FeNode{model=ModelName	,node=595	,x=0	,y=0	,z=134.54	,pMass=001107	,pInertia=0	,pOutOfVertically=01.808}
os_FeNode{model=ModelName	,node=596	,x=0	,y=0	,z=134.59	,pMass=000000	,pInertia=0	,pOutOfVertically=01.809}
os_FeNode{model=ModelName	,node=597	,x=0	,y=0	,z=134.67	,pMass=000000	,pInertia=0	,pOutOfVertically=01.809}

--Definition der FE-Elemente- Zusatzmassen in kg / m
os_FeElem{model=ModelName	,elem_id=001	,startnode=501	,endnode=502	,diameter=5.70	,t_wall=0.030	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=002	,startnode=502	,endnode=503	,diameter=5.70	,t_wall=0.026	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=003	,startnode=503	,endnode=504	,diameter=5.70	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=004	,startnode=504	,endnode=505	,diameter=5.70	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=005	,startnode=505	,endnode=506	,diameter=5.73	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=006	,startnode=506	,endnode=507	,diameter=5.76	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=007	,startnode=507	,endnode=508	,diameter=5.79	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=008	,startnode=508	,endnode=509	,diameter=5.81	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=009	,startnode=509	,endnode=510	,diameter=5.84	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=010	,startnode=510	,endnode=511	,diameter=5.89	,t_wall=0.020	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=011	,startnode=511	,endnode=512	,diameter=5.94	,t_wall=0.020	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=012	,startnode=512	,endnode=513	,diameter=6.00	,t_wall=0.021	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=013	,startnode=513	,endnode=514	,diameter=6.06	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=014	,startnode=514	,endnode=515	,diameter=6.11	,t_wall=0.022	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=015	,startnode=515	,endnode=516	,diameter=6.17	,t_wall=0.023	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=016	,startnode=516	,endnode=517	,diameter=6.19	,t_wall=0.023	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=017	,startnode=517	,endnode=518	,diameter=6.19	,t_wall=0.023	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=018	,startnode=518	,endnode=519	,diameter=6.19	,t_wall=0.023	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=019	,startnode=519	,endnode=520	,diameter=6.19	,t_wall=0.023	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=020	,startnode=520	,endnode=521	,diameter=6.21	,t_wall=0.023	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=021	,startnode=521	,endnode=522	,diameter=6.22	,t_wall=0.024	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=022	,startnode=522	,endnode=523	,diameter=6.24	,t_wall=0.024	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=023	,startnode=523	,endnode=524	,diameter=6.28	,t_wall=0.025	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=024	,startnode=524	,endnode=525	,diameter=6.33	,t_wall=0.026	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=025	,startnode=525	,endnode=526	,diameter=6.39	,t_wall=0.026	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=026	,startnode=526	,endnode=527	,diameter=6.44	,t_wall=0.026	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=027	,startnode=527	,endnode=528	,diameter=6.49	,t_wall=0.027	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=028	,startnode=528	,endnode=529	,diameter=6.55	,t_wall=0.027	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=029	,startnode=529	,endnode=530	,diameter=6.60	,t_wall=0.028	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=030	,startnode=530	,endnode=531	,diameter=6.66	,t_wall=0.029	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=031	,startnode=531	,endnode=532	,diameter=6.71	,t_wall=0.029	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=032	,startnode=532	,endnode=533	,diameter=6.77	,t_wall=0.030	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=033	,startnode=533	,endnode=534	,diameter=6.82	,t_wall=0.030	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=034	,startnode=534	,endnode=535	,diameter=6.87	,t_wall=0.032	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=035	,startnode=535	,endnode=536	,diameter=6.90	,t_wall=0.032	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=036	,startnode=536	,endnode=537	,diameter=6.90	,t_wall=0.032	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=037	,startnode=537	,endnode=538	,diameter=6.90	,t_wall=0.032	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=038	,startnode=538	,endnode=539	,diameter=6.90	,t_wall=0.032	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=039	,startnode=539	,endnode=540	,diameter=6.91	,t_wall=0.032	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=040	,startnode=540	,endnode=541	,diameter=6.94	,t_wall=0.032	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=041	,startnode=541	,endnode=542	,diameter=6.97	,t_wall=0.032	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=042	,startnode=542	,endnode=543	,diameter=7.03	,t_wall=0.033	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=043	,startnode=543	,endnode=544	,diameter=7.08	,t_wall=0.033	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=044	,startnode=544	,endnode=545	,diameter=7.14	,t_wall=0.034	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=045	,startnode=545	,endnode=546	,diameter=7.19	,t_wall=0.034	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=046	,startnode=546	,endnode=547	,diameter=7.24	,t_wall=0.035	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=047	,startnode=547	,endnode=548	,diameter=7.30	,t_wall=0.035	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=048	,startnode=548	,endnode=549	,diameter=7.35	,t_wall=0.036	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=049	,startnode=549	,endnode=550	,diameter=7.40	,t_wall=0.036	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=050	,startnode=550	,endnode=551	,diameter=7.45	,t_wall=0.040	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=051	,startnode=551	,endnode=552	,diameter=7.48	,t_wall=0.040	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=052	,startnode=552	,endnode=553	,diameter=7.48	,t_wall=0.040	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=053	,startnode=553	,endnode=554	,diameter=7.48	,t_wall=0.040	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=054	,startnode=554	,endnode=555	,diameter=7.48	,t_wall=0.040	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=055	,startnode=555	,endnode=556	,diameter=7.48	,t_wall=0.038	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=056	,startnode=556	,endnode=557	,diameter=7.48	,t_wall=0.038	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=057	,startnode=557	,endnode=558	,diameter=7.48	,t_wall=0.039	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=058	,startnode=558	,endnode=559	,diameter=7.48	,t_wall=0.040	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=059	,startnode=559	,endnode=560	,diameter=7.48	,t_wall=0.041	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=060	,startnode=560	,endnode=561	,diameter=7.48	,t_wall=0.042	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=061	,startnode=561	,endnode=562	,diameter=7.48	,t_wall=0.043	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=062	,startnode=562	,endnode=563	,diameter=7.49	,t_wall=0.064	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=063	,startnode=563	,endnode=564	,diameter=7.50	,t_wall=0.064	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=064	,startnode=564	,endnode=565	,diameter=7.50	,t_wall=0.064	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=065	,startnode=565	,endnode=566	,diameter=7.50	,t_wall=0.064	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=066	,startnode=566	,endnode=567	,diameter=7.50	,t_wall=0.064	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=067	,startnode=567	,endnode=568	,diameter=7.50	,t_wall=0.064	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=068	,startnode=568	,endnode=569	,diameter=7.50	,t_wall=0.064	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=069	,startnode=569	,endnode=570	,diameter=8.00	,t_wall=0.102	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=070	,startnode=570	,endnode=571	,diameter=8.00	,t_wall=0.102	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=071	,startnode=571	,endnode=572	,diameter=8.00	,t_wall=0.124	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=072	,startnode=572	,endnode=573	,diameter=8.00	,t_wall=0.125	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=073	,startnode=573	,endnode=574	,diameter=8.00	,t_wall=0.116	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=074	,startnode=574	,endnode=575	,diameter=8.00	,t_wall=0.125	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=075	,startnode=575	,endnode=576	,diameter=8.22	,t_wall=0.125	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=076	,startnode=576	,endnode=577	,diameter=8.66	,t_wall=0.106	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=077	,startnode=577	,endnode=578	,diameter=9.10	,t_wall=0.116	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=078	,startnode=578	,endnode=579	,diameter=9.53	,t_wall=0.103	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=079	,startnode=579	,endnode=580	,diameter=9.97	,t_wall=0.098	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=080	,startnode=580	,endnode=581	,diameter=10.41	,t_wall=0.098	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=081	,startnode=581	,endnode=582	,diameter=10.84	,t_wall=0.098	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=082	,startnode=582	,endnode=583	,diameter=11.28	,t_wall=0.098	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=083	,startnode=583	,endnode=584	,diameter=11.50	,t_wall=0.098	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=084	,startnode=584	,endnode=585	,diameter=11.50	,t_wall=0.100	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=085	,startnode=585	,endnode=586	,diameter=11.50	,t_wall=0.098	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=086	,startnode=586	,endnode=587	,diameter=11.50	,t_wall=0.095	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=087	,startnode=587	,endnode=588	,diameter=11.50	,t_wall=0.095	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=088	,startnode=588	,endnode=589	,diameter=11.50	,t_wall=0.095	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=089	,startnode=589	,endnode=590	,diameter=11.50	,t_wall=0.093	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=090	,startnode=590	,endnode=591	,diameter=11.50	,t_wall=0.093	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=091	,startnode=591	,endnode=592	,diameter=11.50	,t_wall=0.093	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=092	,startnode=592	,endnode=593	,diameter=11.50	,t_wall=0.093	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=093	,startnode=593	,endnode=594	,diameter=11.50	,t_wall=0.096	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=094	,startnode=594	,endnode=595	,diameter=11.50	,t_wall=0.100	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=095	,startnode=595	,endnode=596	,diameter=11.50	,t_wall=0.110	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=096	,startnode=596	,endnode=597	,diameter=11.50	,t_wall=0.122	,EModul=2.10E+11	,fky=355	,poisson=0.3	,dens=7850	,addMass=0	,member_id=1	}
