--Input for JBOOST generated by Excel
--    Definition Modelname
local	ModelName="struct"
--    Definition der FE-Knoten
os_FeNode{model=ModelName	,node=501	,x=0	,y=0	,z=-80.43	,pMass=000000	,pInertia=0	,pOutOfVertically=00.000}
os_FeNode{model=ModelName	,node=502	,x=0	,y=0	,z=-77.43	,pMass=000000	,pInertia=0	,pOutOfVertically=00.039}
os_FeNode{model=ModelName	,node=503	,x=0	,y=0	,z=-74.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.080}
os_FeNode{model=ModelName	,node=504	,x=0	,y=0	,z=-71.00	,pMass=000000	,pInertia=0	,pOutOfVertically=00.123}
os_FeNode{model=ModelName	,node=505	,x=0	,y=0	,z=-67.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.172}
os_FeNode{model=ModelName	,node=506	,x=0	,y=0	,z=-63.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.224}
os_FeNode{model=ModelName	,node=507	,x=0	,y=0	,z=-59.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.277}
os_FeNode{model=ModelName	,node=508	,x=0	,y=0	,z=-55.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.329}
os_FeNode{model=ModelName	,node=509	,x=0	,y=0	,z=-51.70	,pMass=000000	,pInertia=0	,pOutOfVertically=00.376}
os_FeNode{model=ModelName	,node=510	,x=0	,y=0	,z=-48.50	,pMass=000000	,pInertia=0	,pOutOfVertically=00.418}
os_FeNode{model=ModelName	,node=511	,x=0	,y=0	,z=-45.20	,pMass=000000	,pInertia=0	,pOutOfVertically=00.461}
os_FeNode{model=ModelName	,node=512	,x=0	,y=0	,z=-43.30	,pMass=000001	,pInertia=0	,pOutOfVertically=00.483}--added node for pointmass 'dummy to have same number of Bladed nodes as in DP B1 v2'
os_FeNode{model=ModelName	,node=513	,x=0	,y=0	,z=-41.90	,pMass=000000	,pInertia=0	,pOutOfVertically=00.504}
os_FeNode{model=ModelName	,node=514	,x=0	,y=0	,z=-38.60	,pMass=000000	,pInertia=0	,pOutOfVertically=00.548}
os_FeNode{model=ModelName	,node=515	,x=0	,y=0	,z=-35.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.591}
os_FeNode{model=ModelName	,node=516	,x=0	,y=0	,z=-31.80	,pMass=000000	,pInertia=0	,pOutOfVertically=00.637}
os_FeNode{model=ModelName	,node=517	,x=0	,y=0	,z=-28.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.682}
os_FeNode{model=ModelName	,node=518	,x=0	,y=0	,z=-24.80	,pMass=000000	,pInertia=0	,pOutOfVertically=00.728}
os_FeNode{model=ModelName	,node=519	,x=0	,y=0	,z=-21.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.774}
os_FeNode{model=ModelName	,node=520	,x=0	,y=0	,z=-17.80	,pMass=000000	,pInertia=0	,pOutOfVertically=00.820}
os_FeNode{model=ModelName	,node=521	,x=0	,y=0	,z=-14.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.866}
os_FeNode{model=ModelName	,node=522	,x=0	,y=0	,z=-10.80	,pMass=000000	,pInertia=0	,pOutOfVertically=00.911}
os_FeNode{model=ModelName	,node=523	,x=0	,y=0	,z=-7.30	,pMass=000000	,pInertia=0	,pOutOfVertically=00.957}
os_FeNode{model=ModelName	,node=524	,x=0	,y=0	,z=-5.00	,pMass=000001	,pInertia=0	,pOutOfVertically=00.980}--added node for pointmass 'Skirt Lower end'
os_FeNode{model=ModelName	,node=525	,x=0	,y=0	,z=-3.80	,pMass=000000	,pInertia=0	,pOutOfVertically=01.003}
os_FeNode{model=ModelName	,node=526	,x=0	,y=0	,z=-0.60	,pMass=000000	,pInertia=0	,pOutOfVertically=01.045}
os_FeNode{model=ModelName	,node=527	,x=0	,y=0	,z=00.30	,pMass=100000	,pInertia=0	,pOutOfVertically=01.059}--added node for pointmass 'Skirt'
os_FeNode{model=ModelName	,node=528	,x=0	,y=0	,z=02.10	,pMass=000200	,pInertia=0	,pOutOfVertically=01.073}--added node for pointmass 'Internal Access System'
os_FeNode{model=ModelName	,node=529	,x=0	,y=0	,z=02.60	,pMass=000000	,pInertia=0	,pOutOfVertically=01.087}
os_FeNode{model=ModelName	,node=530	,x=0	,y=0	,z=04.20	,pMass=009000	,pInertia=0	,pOutOfVertically=01.101}--added node for pointmass 'Airtight platform'
os_FeNode{model=ModelName	,node=531	,x=0	,y=0	,z=05.60	,pMass=070000	,pInertia=0	,pOutOfVertically=01.115}--added node for pointmass 'TP/MP flange'
os_FeNode{model=ModelName	,node=532	,x=0	,y=0	,z=05.80	,pMass=000000	,pInertia=0	,pOutOfVertically=01.129}
os_FeNode{model=ModelName	,node=533	,x=0	,y=0	,z=09.50	,pMass=000000	,pInertia=0	,pOutOfVertically=01.161}
os_FeNode{model=ModelName	,node=534	,x=0	,y=0	,z=10.00	,pMass=005000	,pInertia=0	,pOutOfVertically=01.178}--added node for pointmass 'Junction Box Platform'
os_FeNode{model=ModelName	,node=535	,x=0	,y=0	,z=13.50	,pMass=000000	,pInertia=0	,pOutOfVertically=01.196}
os_FeNode{model=ModelName	,node=536	,x=0	,y=0	,z=16.10	,pMass=005000	,pInertia=0	,pOutOfVertically=01.207}--added node for pointmass 'Bolting Platform'
os_FeNode{model=ModelName	,node=537	,x=0	,y=0	,z=16.70	,pMass=020000	,pInertia=0	,pOutOfVertically=01.219}--added node for pointmass 'Service Platform'
os_FeNode{model=ModelName	,node=538	,x=0	,y=0	,z=17.47	,pMass=030000	,pInertia=0	,pOutOfVertically=01.231}--placed pointmasse(s) 'TP-sided flange to tower '
os_FeNode{model=ModelName	,node=539	,x=0	,y=0	,z=20.47	,pMass=000000	,pInertia=0	,pOutOfVertically=01.272}
os_FeNode{model=ModelName	,node=540	,x=0	,y=0	,z=23.61	,pMass=000000	,pInertia=0	,pOutOfVertically=01.315}
os_FeNode{model=ModelName	,node=541	,x=0	,y=0	,z=26.91	,pMass=000000	,pInertia=0	,pOutOfVertically=01.360}
os_FeNode{model=ModelName	,node=542	,x=0	,y=0	,z=30.61	,pMass=000000	,pInertia=0	,pOutOfVertically=01.411}
os_FeNode{model=ModelName	,node=543	,x=0	,y=0	,z=34.61	,pMass=000000	,pInertia=0	,pOutOfVertically=01.466}
os_FeNode{model=ModelName	,node=544	,x=0	,y=0	,z=38.61	,pMass=000000	,pInertia=0	,pOutOfVertically=01.521}
os_FeNode{model=ModelName	,node=545	,x=0	,y=0	,z=42.61	,pMass=000000	,pInertia=0	,pOutOfVertically=01.576}
os_FeNode{model=ModelName	,node=546	,x=0	,y=0	,z=46.21	,pMass=000000	,pInertia=0	,pOutOfVertically=01.625}
os_FeNode{model=ModelName	,node=547	,x=0	,y=0	,z=49.41	,pMass=000000	,pInertia=0	,pOutOfVertically=01.669}
os_FeNode{model=ModelName	,node=548	,x=0	,y=0	,z=52.71	,pMass=000000	,pInertia=0	,pOutOfVertically=01.714}
os_FeNode{model=ModelName	,node=549	,x=0	,y=0	,z=54.61	,pMass=000001	,pInertia=0	,pOutOfVertically=01.737}--added node for pointmass 'dummy to have same number of Bladed nodes as in DP B1 v2'
os_FeNode{model=ModelName	,node=550	,x=0	,y=0	,z=56.01	,pMass=000000	,pInertia=0	,pOutOfVertically=01.760}
os_FeNode{model=ModelName	,node=551	,x=0	,y=0	,z=59.31	,pMass=000000	,pInertia=0	,pOutOfVertically=01.805}
os_FeNode{model=ModelName	,node=552	,x=0	,y=0	,z=62.61	,pMass=000000	,pInertia=0	,pOutOfVertically=01.850}
os_FeNode{model=ModelName	,node=553	,x=0	,y=0	,z=66.11	,pMass=000000	,pInertia=0	,pOutOfVertically=01.898}
os_FeNode{model=ModelName	,node=554	,x=0	,y=0	,z=69.61	,pMass=000000	,pInertia=0	,pOutOfVertically=01.946}
os_FeNode{model=ModelName	,node=555	,x=0	,y=0	,z=73.11	,pMass=000000	,pInertia=0	,pOutOfVertically=01.994}
os_FeNode{model=ModelName	,node=556	,x=0	,y=0	,z=76.61	,pMass=000000	,pInertia=0	,pOutOfVertically=02.042}
os_FeNode{model=ModelName	,node=557	,x=0	,y=0	,z=80.11	,pMass=000000	,pInertia=0	,pOutOfVertically=02.090}
os_FeNode{model=ModelName	,node=558	,x=0	,y=0	,z=83.61	,pMass=000000	,pInertia=0	,pOutOfVertically=02.138}
os_FeNode{model=ModelName	,node=559	,x=0	,y=0	,z=87.11	,pMass=000000	,pInertia=0	,pOutOfVertically=02.186}
os_FeNode{model=ModelName	,node=560	,x=0	,y=0	,z=90.61	,pMass=000000	,pInertia=0	,pOutOfVertically=02.234}
os_FeNode{model=ModelName	,node=561	,x=0	,y=0	,z=92.91	,pMass=000001	,pInertia=0	,pOutOfVertically=02.259}--added node for pointmass 'Skirt Lower end'
os_FeNode{model=ModelName	,node=562	,x=0	,y=0	,z=94.11	,pMass=000000	,pInertia=0	,pOutOfVertically=02.283}
os_FeNode{model=ModelName	,node=563	,x=0	,y=0	,z=97.31	,pMass=000000	,pInertia=0	,pOutOfVertically=02.326}
os_FeNode{model=ModelName	,node=564	,x=0	,y=0	,z=98.21	,pMass=100000	,pInertia=0	,pOutOfVertically=02.348}--added node for pointmass 'Skirt'
os_FeNode{model=ModelName	,node=565	,x=0	,y=0	,z=100.51	,pMass=000000	,pInertia=0	,pOutOfVertically=02.370}
os_FeNode{model=ModelName	,node=566	,x=0	,y=0	,z=102.11	,pMass=009000	,pInertia=0	,pOutOfVertically=02.385}--added node for pointmass 'Airtight platform'
os_FeNode{model=ModelName	,node=567	,x=0	,y=0	,z=103.51	,pMass=070000	,pInertia=0	,pOutOfVertically=02.400}--added node for pointmass 'TP/MP flange'
os_FeNode{model=ModelName	,node=568	,x=0	,y=0	,z=103.71	,pMass=000000	,pInertia=0	,pOutOfVertically=02.414}

--Definition der FE-Elemente- Zusatzmassen in kg / m
os_FeElem{model=ModelName	,elem_id=001	,startnode=501	,endnode=502	,diameter=8.00	,t_wall=0.115	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=002	,startnode=502	,endnode=503	,diameter=8.00	,t_wall=0.115	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=003	,startnode=503	,endnode=504	,diameter=8.00	,t_wall=0.115	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=004	,startnode=504	,endnode=505	,diameter=8.00	,t_wall=0.115	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=005	,startnode=505	,endnode=506	,diameter=8.00	,t_wall=0.115	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=006	,startnode=506	,endnode=507	,diameter=8.00	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=007	,startnode=507	,endnode=508	,diameter=8.22	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=008	,startnode=508	,endnode=509	,diameter=8.30	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=009	,startnode=509	,endnode=510	,diameter=8.66	,t_wall=0.106	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=010	,startnode=510	,endnode=511	,diameter=9.10	,t_wall=0.116	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=011	,startnode=511	,endnode=512	,diameter=9.53	,t_wall=0.103	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=012	,startnode=512	,endnode=513	,diameter=9.97	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=013	,startnode=513	,endnode=514	,diameter=10.32	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=014	,startnode=514	,endnode=515	,diameter=10.84	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=015	,startnode=515	,endnode=516	,diameter=11.28	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=016	,startnode=516	,endnode=517	,diameter=11.50	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=017	,startnode=517	,endnode=518	,diameter=11.50	,t_wall=0.100	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=018	,startnode=518	,endnode=519	,diameter=11.50	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=019	,startnode=519	,endnode=520	,diameter=11.50	,t_wall=0.095	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=020	,startnode=520	,endnode=521	,diameter=11.50	,t_wall=0.095	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=021	,startnode=521	,endnode=522	,diameter=11.50	,t_wall=0.095	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=022	,startnode=522	,endnode=523	,diameter=11.50	,t_wall=0.095	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=023	,startnode=523	,endnode=524	,diameter=11.50	,t_wall=0.093	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=024	,startnode=524	,endnode=525	,diameter=11.50	,t_wall=0.093	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=025	,startnode=525	,endnode=526	,diameter=11.50	,t_wall=0.093	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=026	,startnode=526	,endnode=527	,diameter=11.50	,t_wall=0.093	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=027	,startnode=527	,endnode=528	,diameter=11.50	,t_wall=0.096	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=028	,startnode=528	,endnode=529	,diameter=11.50	,t_wall=0.096	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=029	,startnode=529	,endnode=530	,diameter=11.50	,t_wall=0.100	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=030	,startnode=530	,endnode=531	,diameter=11.50	,t_wall=0.105	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=031	,startnode=531	,endnode=532	,diameter=8.00	,t_wall=0.102	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=032	,startnode=532	,endnode=533	,diameter=8.00	,t_wall=0.102	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=033	,startnode=533	,endnode=534	,diameter=8.00	,t_wall=0.102	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=034	,startnode=534	,endnode=535	,diameter=8.00	,t_wall=0.102	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=035	,startnode=535	,endnode=536	,diameter=8.00	,t_wall=0.102	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=036	,startnode=536	,endnode=537	,diameter=8.00	,t_wall=0.124	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=037	,startnode=537	,endnode=538	,diameter=8.00	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=038	,startnode=538	,endnode=539	,diameter=8.00	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=039	,startnode=539	,endnode=540	,diameter=8.00	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=040	,startnode=540	,endnode=541	,diameter=8.00	,t_wall=0.116	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=041	,startnode=541	,endnode=542	,diameter=8.00	,t_wall=0.116	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=042	,startnode=542	,endnode=543	,diameter=8.00	,t_wall=0.116	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=043	,startnode=543	,endnode=544	,diameter=8.00	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=044	,startnode=544	,endnode=545	,diameter=8.22	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=045	,startnode=545	,endnode=546	,diameter=8.30	,t_wall=0.125	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=046	,startnode=546	,endnode=547	,diameter=8.66	,t_wall=0.106	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=047	,startnode=547	,endnode=548	,diameter=9.10	,t_wall=0.116	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=048	,startnode=548	,endnode=549	,diameter=9.53	,t_wall=0.103	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=049	,startnode=549	,endnode=550	,diameter=9.97	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=050	,startnode=550	,endnode=551	,diameter=10.41	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=051	,startnode=551	,endnode=552	,diameter=10.84	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=052	,startnode=552	,endnode=553	,diameter=11.28	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=053	,startnode=553	,endnode=554	,diameter=11.50	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=054	,startnode=554	,endnode=555	,diameter=11.50	,t_wall=0.100	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=055	,startnode=555	,endnode=556	,diameter=11.50	,t_wall=0.098	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=056	,startnode=556	,endnode=557	,diameter=11.50	,t_wall=0.095	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=057	,startnode=557	,endnode=558	,diameter=11.50	,t_wall=0.095	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=058	,startnode=558	,endnode=559	,diameter=11.50	,t_wall=0.095	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=059	,startnode=559	,endnode=560	,diameter=11.50	,t_wall=0.095	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=060	,startnode=560	,endnode=561	,diameter=11.50	,t_wall=0.093	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=061	,startnode=561	,endnode=562	,diameter=11.50	,t_wall=0.093	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=062	,startnode=562	,endnode=563	,diameter=11.50	,t_wall=0.093	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=063	,startnode=563	,endnode=564	,diameter=11.50	,t_wall=0.093	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=064	,startnode=564	,endnode=565	,diameter=11.50	,t_wall=0.096	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=065	,startnode=565	,endnode=566	,diameter=11.50	,t_wall=0.100	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=066	,startnode=566	,endnode=567	,diameter=11.50	,t_wall=0.110	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
os_FeElem{model=ModelName	,elem_id=067	,startnode=567	,endnode=568	,diameter=11.50	,t_wall=0.122	,EModul=210000000000.0	,fky=355	,poisson=0.3	,dens=7850.0	,addMass=0	,member_id=1	}
