--Input for WLGen generated by Excel

--data for monopile sections: vertical positions z_bot and z_top are relative to design water level. Dimensions in meters.
Data_MonopileSections{ diameter_bot =  8.000,  diameter_top = 8.000,  wall_thickness = 0.115,  z_bot = 2.600,  z_top = 5.800,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  8.000,  diameter_top = 8.000,  wall_thickness = 0.115,  z_bot = -0.600,  z_top = 2.600,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  8.000,  diameter_top = 8.000,  wall_thickness = 0.125,  z_bot = -3.800,  z_top = -0.600,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  8.440,  diameter_top = 8.000,  wall_thickness = 0.125,  z_bot = -7.300,  z_top = -3.800,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  8.880,  diameter_top = 8.440,  wall_thickness = 0.106,  z_bot = -10.800,  z_top = -7.300,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  9.310,  diameter_top = 8.880,  wall_thickness = 0.116,  z_bot = -14.300,  z_top = -10.800,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  9.750,  diameter_top = 9.310,  wall_thickness = 0.103,  z_bot = -17.800,  z_top = -14.300,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  10.190,  diameter_top = 9.750,  wall_thickness = 0.098,  z_bot = -21.300,  z_top = -17.800,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  10.630,  diameter_top = 10.190,  wall_thickness = 0.098,  z_bot = -24.800,  z_top = -21.300,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  11.060,  diameter_top = 10.630,  wall_thickness = 0.098,  z_bot = -28.300,  z_top = -24.800,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  11.500,  diameter_top = 11.060,  wall_thickness = 0.098,  z_bot = -31.800,  z_top = -28.300,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  11.500,  diameter_top = 11.500,  wall_thickness = 0.098,  z_bot = -35.300,  z_top = -31.800,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  11.500,  diameter_top = 11.500,  wall_thickness = 0.100,  z_bot = -38.600,  z_top = -35.300,  surface_roughness = 0, }
Data_MonopileSections{ diameter_bot =  11.500,  diameter_top = 11.500,  wall_thickness = 0.098,  z_bot = -39.800,  z_top = -38.600,  surface_roughness = 0, }

--data for transition-piece sections: vertical positions z_bot and z_top are relative to design water level. Dimensions in meters.
Data_TransitionPieceSections{ diameter_bot =  8.000,  diameter_top = 8.000,  wall_thickness = 0.117,  z_bot = 17.500,  z_top = 21.470,  surface_roughness = 0, }
Data_TransitionPieceSections{ diameter_bot =  8.000,  diameter_top = 8.000,  wall_thickness = 0.117,  z_bot = 13.500,  z_top = 17.500,  surface_roughness = 0, }
Data_TransitionPieceSections{ diameter_bot =  8.000,  diameter_top = 8.000,  wall_thickness = 0.124,  z_bot = 9.500,  z_top = 13.500,  surface_roughness = 0, }
Data_TransitionPieceSections{ diameter_bot =  8.000,  diameter_top = 8.000,  wall_thickness = 0.120,  z_bot = 5.800,  z_top = 9.500,  surface_roughness = 0, }

--data for additional masses: vertical positions z are relative to design water level.
Data_Masses_Monopile_TransitionPiece{ id = "TP-sided flange to tower",  z =  21.470,  mass =  30000.0, }
Data_Masses_Monopile_TransitionPiece{ id = "Service Platform",  z =  20.700,  mass =  20000.0, }
Data_Masses_Monopile_TransitionPiece{ id = "Bolting Platform",  z =  20.100,  mass =  5000.0, }
Data_Masses_Monopile_TransitionPiece{ id = "Junction Box Platform",  z =  14.000,  mass =  5000.0, }

--data for appurtenances: vertical positions z_bot and z_top are relative to design water level. Dimensions in meters, with the exception of orientation in degree from North and mass in kg.
 Data_Appurtenances{ id = "Upper ladder",  z_bot = 9.600,  z_top = 16.500,  diameter = 0.152,  orientation = 100.400,  mass = 1000.0,  distance_axis_to_axis = 4.215,  surface_roughness = 0.000 }
 Data_Appurtenances{ id = "Upper ladder",  z_bot = 9.600,  z_top = 16.500,  diameter = 0.152,  orientation = 109.600,  mass = 1000.0,  distance_axis_to_axis = 4.215,  surface_roughness = 0.000 }
 Data_Appurtenances{ id = "Lower ladder",  z_bot = -2.100,  z_top = 12.000,  diameter = 0.194,  orientation = 85.200,  mass = 1250.0,  distance_axis_to_axis = 4.0,  surface_roughness = 0.000 }
 Data_Appurtenances{ id = "Lower ladder",  z_bot = -2.100,  z_top = 12.000,  diameter = 0.194,  orientation = 94.800,  mass = 1250.0,  distance_axis_to_axis = 4.215,  surface_roughness = 0.000 }
 Data_Appurtenances{ id = "Fender",  z_bot = -2.100,  z_top = 9.500,  diameter = 0.422,  orientation = 79.500,  mass = 4250.0,  distance_axis_to_axis = 4.93,  surface_roughness = 0.000 }
 Data_Appurtenances{ id = "Fender",  z_bot = -2.100,  z_top = 9.500,  diameter = 0.422,  orientation = 100.500,  mass = 4250.0,  distance_axis_to_axis = 4.93,  surface_roughness = 0.000 }
 Data_Appurtenances{ id = "Resting platform",  z_bot = 9.600,  z_top = 10.200,  diameter = 1.200,  orientation = 105.000,  mass = 2500.0,  gap_between_surfaces = 4.93,  surface_roughness = 0.000 }

--data for marine growth: thickness up to defined vertical positions, relative to design water level, both in meters. The thickness is zero above the last given vertical position. Density in kg/m3.
Data_MarineGrowth{ z_bot = "139.0",  z_top =  4.600,  thickness =  0.000,  density =  1325,  surface_roughness =  0.500, }
Data_MarineGrowth{ z_bot = "4.6",  z_top =  -9.600,  thickness =  0.250,  density =  1325,  surface_roughness =  0.500, }
Data_MarineGrowth{ z_bot = "-9.6",  z_top =  -22.000,  thickness =  0.100,  density =  1325,  surface_roughness =  0.500, }